# Generated by Django 5.2.6 on 2025-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome do arquivo enviado', max_length=255)),
                ('arquivo', models.FileField(help_text='O arquivo CSV em si', upload_to='uploads/')),
                ('data_upload', models.DateTimeField(auto_now_add=True, help_text='Data e hora do upload')),
            ],
            options={
                'verbose_name': 'Upload de Arquivo',
                'verbose_name_plural': 'Uploads de Arquivos',
            },
        ),
    ]
