# Generated by Django 5.2.6 on 2025-09-19 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadArquivo",
        ),
    ]
